/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xml;


import java.util.List;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.Result;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.DOMImplementation;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Text;

/**
 *
 * @author Dalto
 */
public class Jxml extends javax.swing.JFrame {

    public String documento;
    private String cedulas;
    private String retornoXML="";
    /**
     * Creates new form Jxml
     */
    public Jxml() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_generar = new javax.swing.JButton();
        btn_abrir = new javax.swing.JButton();
        btn_subir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_consulta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_enlace = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_generar.setText("GENERAR");

        btn_abrir.setText("ABRIR");

        btn_subir.setText("SUBIR");

        jLabel1.setText("REGISTRAR CLIENTES");

        btn_consulta.setText("Consultar");

        jLabel2.setText("Cedula:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellido:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_enlace)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(65, 65, 65)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_cedula)
                                    .addComponent(txt_nombre)
                                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_consulta)
                            .addComponent(btn_abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1))
                    .addComponent(btn_subir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_generar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_consulta))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_generar)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_enlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_abrir))
                .addGap(32, 32, 32)
                .addComponent(btn_subir)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jxml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jxml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jxml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jxml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jxml().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_abrir;
    public javax.swing.JButton btn_consulta;
    public javax.swing.JButton btn_generar;
    public javax.swing.JButton btn_subir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txt_apellido;
    public javax.swing.JTextField txt_cedula;
    public javax.swing.JTextField txt_enlace;
    public javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables

    private void generarXML(String cedulas, String nombres, String apellidos) {
        try {
            DocumentBuilderFactory builderFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = builderFactory.newDocumentBuilder();
            DOMImplementation dOMImplementation = builder.getDOMImplementation();
            
            // Creación de un nuevo documento XML con el elemento raíz "Personas".
            Document document = dOMImplementation.createDocument(null, "Personas", null);
            document.setXmlVersion("1.0");
            // Resultado:
            /*
            * <?xml version="1.0" encoding="UTF-8"?>
            * <Personas>
            *           ---
            * <Personas>
            */

            // Creando un nuevo elemento llamado "persona"
            Element persona = document.createElement("persona");
            // Resultado:
            /*
            * <?xml version="1.0" encoding="UTF-8"?>
            * <Personas>
            *      <persona>
            *            -----
            *      </persona>
            * <Personas>
            */
            
            // Se crea un elemento llamado cedula
            Element cedula = document.createElement("cedula");
            // Se crea nodo texto llamado txtCedula y se guarda el valor de la variable cedulas
            Text txtCedula = document.createTextNode(cedulas);
            // El nodo de texto txtCedula se agrega al elemento cedula.
            cedula.appendChild(txtCedula);
            // El elemento cedula se agrega al elemento persona.
            persona.appendChild(cedula);
            // Resultado:
            /*
            * <?xml version="1.0" encoding="UTF-8"?>
            * <Personas>
            *      <persona>
            *            <cedula>Valor del nodo texto txtCedula</cedula>
            *      </persona>
            * <Personas>
            */

            // Agregamos mas elementos como sea necesario
            Element nombre = document.createElement("nombre");
            Text txtNombre = document.createTextNode(nombres);
            nombre.appendChild(txtNombre);
            persona.appendChild(nombre);

            Element apellido = document.createElement("apellido");
            Text txtApellido = document.createTextNode(apellidos);
            apellido.appendChild(txtApellido);
            persona.appendChild(apellido);
            
            // El elemento persona se agrega al elemento raiz.
            document.getDocumentElement().appendChild(persona);
            
            //Resultado:
            /*
            * <?xml version="1.0" encoding="UTF-8"?>
            * <Personas>
            *      <persona>
            *            <cedula>Valor del nodo texto txtCedula</cedula>
            *            <nombre>Valor del nodo texto txtNombre</nombre>
            *            <apellido>Valor del nodo texto txtApellido</apellido>
            *      </persona>
            * <Personas>
            */

            // Generamos el archivo xml con los datos anteriores
            // Se guarda en la carpeta del proyecto
            Source source = new DOMSource(document);
            // En la variable documento esta guardado el numero de cedula con la extencion xml
            Result result = new StreamResult(new File(documento));
            
            Transformer transformer = TransformerFactory.newInstance().newTransformer();
            transformer.transform(source, result);
            
            JOptionPane.showMessageDialog(null, "Se ha generado con exito.");
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private static String insertar(java.lang.String file) {
        wsXML.NewWebService_Service service = new wsXML.NewWebService_Service();
        wsXML.NewWebService port = service.getNewWebServicePort();
        return port.insertar(file);
    }

    private static java.util.List<java.lang.String> consulta(java.lang.String cedula) {
        wsXML.NewWebService_Service service = new wsXML.NewWebService_Service();
        wsXML.NewWebService port = service.getNewWebServicePort();
        return port.consulta(cedula);
    }
}